name: clue_notepad
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.0.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.1.2
  package_info_plus: ^4.2.0
  flutter_oss_licenses: ^3.0.2
  flutter_native_splash: ^2.4.0
  url_launcher: ^6.1.2
  auto_size_text: ^3.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/icon/icon.png
  color: "#42a5f5"
  android: true
  ios: false

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo.png
